### DISCUSSION TITLE
Automation for Resuming Operation of the Mower and Ensuring Continuous Functionality

### DISCUSSION THREAD

**Discussion by AlohaFlyer** [mikey0000/Mammotion-HA#219] [Show and tell]
The Luba 2 occasionally pauses unexpectedly, even when placed on the docking station. This automation monitors for such instances and automatically resets the Luba 2 to Continue mode.

```
alias: Mower - PAUSED - Continue
description: ""
triggers:
  - trigger: time_pattern
    minutes: /5
conditions:
  - condition: state
    entity_id: lawn_mower.luba_vs2gq8kb
    state: paused
    for:
      hours: 0
      minutes: 1
      seconds: 0
  - condition: numeric_state
    entity_id: sensor.luba_vs2gq8kb_battery
    above: 99
  - condition: numeric_state
    entity_id: sensor.luba_vs2gq8kb_progress
    below: 100
actions:
  - action: lawn_mower.start_mowing
    metadata: {}
    data: {}
    target:
      entity_id: lawn_mower.luba_vs2gq8kb
mode: single
```
