### DISCUSSION TITLE
Automation to Open Gate, so Luba 2 can mow the front driveway area

### DISCUSSION THREAD

**Discussion by AlohaFlyer** [mikey0000/Mammotion-HA#220] [Q&A]
I have a long driveway and front area outside of my gate, that I want Luba 2 to mow. What would be the best way to trigger an automation that can open my gate? 

One thought was to make a mowing area that straddles the gate that stretches 3-4 meters on either side of the gate, then trigger the automation to open when it reaches this area. I just need to find a way to trigger that. I don't think there is a sensor that can give me that info reliably. 

Thoughts??

**Comment by Kontendesigner** [comment]
I have a similar configuration.

My Luba is in the garage and should park/charge there again after mowing. To do this, I trigger the activity mode. As soon as it changes to "MODE_RETURNING", the garage door is opened.

You can trigger as well on position "channel_on"

```
triggers:
  - trigger: state
    entity_id:
      - sensor.luba_dalos_aktivitatsmodus
    to: MODE_RETURNING
    from: null

```
