### DISCUSSION TITLE
Lawn mower card

### DISCUSSION THREAD

**Discussion by albatorsk** [mikey0000/Mammotion-HA#285] [General]
I'm just curious what lawn mower cards or custom dashboard you're using in HA for this integration. I've tried [the](https://github.com/cociweb/lawn-mower-card) but couldn't get it to work. It doesn't show anything.

Thank you.

**Comment by jgreferee** [comment]
I use the standard lawn mower card and control my Luba with it. But what I miss is the opportunity to click on the mower picture and then view the zones that I have mapped.
![Lawn mower card](https://github.com/user-attachments/assets/0192abb2-314d-44e5-a505-69cfeef1f983)

**Comment by albatorsk** [comment]
Is that the custom card I linked to? There is no "standard" lawn mower card i HA.

**Reply by mikey0000** [reply]
Yes there is now, lawn mower card is the entity card

**Reply by albatorsk** [reply]
![Screenshot From 2025-04-24 11-33-02](https://github.com/user-attachments/assets/fd755d88-646c-4c55-af39-91a7501a9d9f)
![Screenshot From 2025-04-24 11-32-49](https://github.com/user-attachments/assets/50d5e8d5-e9c6-44ef-bd42-dd69097b9a8e)
I feel like I'm going crazy here, but there really is no lawn mower card in my HA, version 2025.4.3.

**Reply by mikey0000** [reply]
Add by entity, OK so it isn't labeled as a mower card

**Comment by imonlinux** [comment]
I have just started using the Ultra Vehicle Card from HACS. I haven't added any of the controls yet, but that is an option.

https://github.com/WJDDesigns/Ultra-Vehicle-Card

![Screenshot From 2025-04-24 08-59-02](https://github.com/user-attachments/assets/d3e129e0-8a13-4a5f-ac17-458561495ad8)

The image can be changed based on the state of an entity.

![screensharing](https://github.com/user-attachments/assets/58108869-5e3a-4352-8bb1-64e53aea61d2)

**Reply by albatorsk** [reply]
Funny, I was already using UVC for my car, but I had not thought of the idea that it can be used for my mower as well. Thanks for the tip!

**Reply by imonlinux** [reply]
I just thought about it this week. I'm adding my vacuum and mop next.

**Comment by JoshFDXGUS** [comment]
I too am using the Vehicle Card

<img width="853" height="749" alt="image" src="https://github.com/user-attachments/assets/194e02fb-4ced-476b-bf1b-af682bc76562" />

**Reply by fabiangranig** [reply]
How did you get the map on the right?

**Reply by dvptommy** [reply]
Use the Map card and add the mower to it as a tracked device.

**Reply by fabiangranig** [reply]
Can't find the card. Is it coming from another addon? Could you share an screenshot?

**Reply by HeyITGuyFixIt** [reply]
Should be the built-in map card. Just add the mower as an entity to the card. 

<img width="863" height="1373" alt="ResizedImage_2025-12-07_22-59-51_1252" src="https://github.com/user-attachments/assets/61f86927-17e5-452f-a150-07794710fac7" />

**Comment by lorenzo-randisi** [comment]
Hi everyone, here's my card 😄 

https://github.com/user-attachments/assets/08c61a93-1097-48ce-836a-177b7d5c80ba

**Reply by mikey0000** [reply]
any chance you can supply the yaml / config for this if anyone wants to replicate it?

**Reply by lorenzo-randisi** [reply]
Sure! it's the least I can do ❤️ 

```yaml
type: picture-elements
image: /local/LUBAminiAWD.jpg
aspect_ratio: "1:1"
card_mod:
  style: |
    ha-card {
      border-radius: 16px;
      overflow: hidden;
      height: 360px;
    }
elements:
  - type: custom:button-card
    name: PAUSA
    icon: mdi:pause-circle
    style:
      left: 15%
      top: 39%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: lawn_mower.pause
      target:
        entity_id: lawn_mower.luba_mna68x8t
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: "#f59e0b"
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,0.6)
  - type: custom:button-card
    name: AVVIA
    icon: mdi:play-circle
    style:
      left: 15%
      top: 14%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: input_button.press
      target:
        entity_id: input_button.luba_start_falciatura
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: "#22c55e"
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,1)
  - type: custom:button-card
    name: TERMINA
    icon: mdi:close-octagon
    style:
      left: 15%
      top: 59%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: mammotion.cancel_job
      target:
        entity_id: lawn_mower.luba_mna68x8t
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: red
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,0.6)
  - type: custom:button-card
    name: BASE
    icon: mdi:home-import-outline
    style:
      left: 15%
      top: 80%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: script.luba_annulla_e_torna_alla_base
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: "#3b82f6"
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,0.6)
  - type: custom:button-card
    entity: input_boolean.retro
    name: RETRO
    icon: mdi:grass
    style:
      left: 40%
      top: 14%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.retro
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: "#22c55e"
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,1)
    state:
      - value: "on"
        styles:
          card:
            - background-color: rgba(245,158,11,0.35)
            - box-shadow: 0 0 0 2px rgba(245,158,11,0.6), 0 6px 18px rgba(0,0,0,0.35)
  - type: custom:button-card
    entity: input_boolean.ingresso
    name: INGRESSO
    icon: mdi:grass
    style:
      left: 62.6%
      top: 14%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.ingresso
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: "#22c55e"
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,1)
    state:
      - value: "on"
        styles:
          card:
            - background-color: rgba(245,158,11,0.35)
            - box-shadow: 0 0 0 2px rgba(245,158,11,0.6), 0 6px 18px rgba(0,0,0,0.35)
  - type: custom:button-card
    entity: input_boolean.cancello
    name: CANCELLO
    icon: mdi:grass
    style:
      left: 85%
      top: 14%
      transform: translate(-50%, -50%)
    tap_action:
      action: call-service
      service: input_boolean.toggle
      target:
        entity_id: input_boolean.cancello
    styles:
      card:
        - background: none
        - box-shadow: none
        - border: none
        - padding: 0
        - width: 100px
      grid:
        - grid-template-areas: "\"i\" \"n\""
        - place-items: center
        - row-gap: 4px
      icon:
        - width: 60px
        - height: 60px
        - color: "#22c55e"
      name:
        - color: white
        - font-weight: 700
        - font-size: 15px
        - text-shadow: 0 2px 6px rgba(0,0,0,1)
    state:
      - value: "on"
        styles:
          card:
            - background-color: rgba(245,158,11,0.35)
            - box-shadow: 0 0 0 2px rgba(245,158,11,0.6), 0 6px 18px rgba(0,0,0,0.35)
  - type: custom:button-card
    entity: sensor.luba_mna68x8t_progresso
    show_icon: false
    show_name: false
    show_state: false
    style:
      left: 64%
      top: 27%
      transform: translate(-50%, -50%)
    custom_fields:
      bar: |
        [[[
          const s = states['sensor.luba_mna68x8t_progresso'];
          let v = s && s.state && s.state !== 'unknown' && s.state !== 'unavailable'
            ? parseInt(s.state)
            : 0;

          if (isNaN(v)) v = 0;
          v = Math.max(0, Math.min(100, v));

          return `
            <div class="bar-outer">
              <div class="bar-label">${v}%</div>
              <div class="bar-inner" style="width:${v}%"></div>
            </div>
          `;
        ]]]
    styles:
      card:
        - background: none
        - border: none
        - box-shadow: none
        - padding: 0
        - width: auto
      grid:
        - grid-template-areas: "\"bar\""
        - place-items: center
      custom_fields:
        bar:
          - width: 240px
    extra_styles: |
      .bar-outer {
        position: relative;
        width: 100%;
        height: 15px;
        background: rgba(255,255,255,0.25);
        border-radius: 9999px;
        overflow: hidden;
      }
      .bar-inner {
        height: 100%;
        background: linear-gradient(90deg, rgba(59,130,246,1), rgba(59,130,246,0.85));
        border-radius: 9999px;
        transition: width 0.4s ease;
      }
      .bar-label {
        position: absolute;
        left: 8px;
        top: 50%;
        transform: translateY(-50%);
        font-weight: 800;
        font-size: 11px;
        color: #ffffff;
        text-shadow: 0 1px 3px rgba(0,0,0,0.6);
        pointer-events: none;
      }
    triggers_update:
      - sensor.luba_mna68x8t_progresso
  - type: custom:button-card
    entity: input_number.luba_ultimo_progresso
    show_icon: false
    show_name: false
    show_state: false
    style:
      left: 64%
      top: 41%
      transform: translate(-50%, -50%)
    custom_fields:
      info: |
        [[[
          const prog = states['input_number.luba_ultimo_progresso'];
          let p = prog && prog.state && prog.state !== 'unknown' && prog.state !== 'unavailable'
            ? parseInt(prog.state)
            : null;

          const progresso = (p !== null && !isNaN(p)) ? `${p}%` : 'N/D';

          return `
            <div class="luba-box">
              <div class="luba-title">ULTIMO PROGRESSO SALVATO</div>
              <div class="luba-row single">
                <span class="value">${progresso}</span>
              </div>
            </div>
          `;
        ]]]
    styles:
      card:
        - background: rgba(31,41,55,0.82)
        - border-radius: 14px
        - border: none
        - box-shadow: 0 6px 18px rgba(0,0,0,0.35)
        - padding: 8px 12px
        - width: 240px
        - display: |
            [[[
              const r = states['input_boolean.luba_rientro_in_carica'];
              return (r && r.state === 'on') ? 'block' : 'none';
            ]]]
      grid:
        - grid-template-areas: "\"info\""
        - place-items: center
      custom_fields:
        info:
          - width: 100%
    extra_styles: |
      .luba-box {
        width: 100%;
        color: white;
      }
      .luba-title {
        font-size: 11px;
        font-weight: 800;
        letter-spacing: 0.8px;
        margin-bottom: 6px;
        opacity: 0.95;
      }
      .luba-row {
        display: flex;
        justify-content: space-between;
        align-items: center;
        font-size: 12px;
        line-height: 1.4;
        margin: 2px 0;
      }
      .luba-row.single {
        justify-content: center;
      }
      .luba-row .value {
        font-weight: 800;
        font-size: 16px;
      }
    triggers_update:
      - input_number.luba_ultimo_progresso
      - input_boolean.luba_rientro_in_carica
  - type: custom:button-card
    entity: input_boolean.luba_rientro_in_carica
    show_icon: false
    show_name: false
    show_state: false
    style:
      left: 64%
      top: 29%
      transform: translate(-50%, -50%)
    custom_fields:
      info: |
        [[[
          return `
            <div class="luba-box">
              <div class="luba-title">AVVISO</div>
              <div class="luba-message">
                Il Luba è in pausa batteria
              </div>
            </div>
          `;
        ]]]
    styles:
      card:
        - background: rgba(59,130,246,0.88)
        - border-radius: 14px
        - border: none
        - box-shadow: 0 6px 18px rgba(0,0,0,0.35)
        - padding: 8px 12px
        - width: 240px
        - display: |
            [[[
              const r = states['input_boolean.luba_rientro_in_carica'];
              return (r && r.state === 'on') ? 'block' : 'none';
            ]]]
      grid:
        - grid-template-areas: "\"info\""
        - place-items: center
      custom_fields:
        info:
          - width: 100%
    extra_styles: |
      .luba-box {
        width: 100%;
        color: white;
      }
      .luba-title {
        font-size: 11px;
        font-weight: 800;
        letter-spacing: 0.8px;
        margin-bottom: 6px;
        opacity: 0.95;
      }
      .luba-message {
        font-size: 12px;
        line-height: 1.35;
        font-weight: 600;
      }
    triggers_update:
      - input_boolean.luba_rientro_in_carica
  - type: custom:button-card
    entity: sensor.luba_mna68x8t_batteria
    show_icon: true
    show_name: true
    show_state: false
    style:
      left: 70%
      top: 57%
      transform: translate(-50%, -50%)
    name: |
      [[[
        const s = states['sensor.luba_mna68x8t_batteria'];
        const v = s && s.state && s.state !== 'unknown' && s.state !== 'unavailable'
          ? parseInt(s.state)
          : null;
        return v != null ? `${v}%` : 'N/D';
      ]]]
    icon: |
      [[[
        const batt = states['sensor.luba_mna68x8t_batteria'];
        let p = batt && batt.state && batt.state !== 'unknown' && batt.state !== 'unavailable'
          ? parseInt(batt.state)
          : null;

        const ch = states['binary_sensor.luba_mna68x8t_in_ricarica'];
        const isCharging = ch && ch.state === 'on';

        if (p == null || isNaN(p)) return 'mdi:battery-unknown';
        p = Math.max(0, Math.min(100, p));

        if (isCharging) {
          if (p <= 5) return 'mdi:battery-charging-outline';
          const step = Math.round(p / 10) * 10;
          return step >= 100 ? 'mdi:battery-charging' : `mdi:battery-charging-${step}`;
        }

        if (p <= 5) return 'mdi:battery-outline';
        const step = Math.round(p / 10) * 10;
        return step >= 100 ? 'mdi:battery' : `mdi:battery-${step}`;
      ]]]
    styles:
      card:
        - border: none
        - padding: 6px 10px
        - border-radius: 9999px
        - width: auto
        - box-shadow: 0 6px 18px rgba(0,0,0,0.35)
        - background-color: |
            [[[
              const s = states['sensor.luba_mna68x8t_batteria'];
              let p = s && s.state && s.state !== 'unknown' && s.state !== 'unavailable'
                ? parseInt(s.state)
                : null;

              if (p == null || isNaN(p)) return 'rgba(31,41,55,0.85)';
              if (p < 30) return 'rgba(239,68,68,0.90)';
              if (p < 60) return 'rgba(245,158,11,0.90)';
              return 'rgba(34,197,94,0.90)';
            ]]]
      grid:
        - grid-template-areas: "\"i n\""
        - grid-template-columns: min-content 1fr
        - place-items: center
        - column-gap: 6px
      icon:
        - width: 16px
        - height: 16px
        - color: white
        - top: "-3px"
      name:
        - color: white
        - font-weight: 800
        - font-size: 12px
    triggers_update:
      - sensor.luba_mna68x8t_batteria
      - binary_sensor.luba_mna68x8t_in_ricarica
  - type: conditional
    conditions:
      - entity: input_boolean.luba_blocco_parametri
        state: "on"
    elements:
      - type: custom:button-card
        name: ESCI DALLA BASE
        icon: mdi:home-export-outline
        style:
          left: 40%
          top: 40%
          transform: translate(-50%, -50%)
        tap_action:
          action: call-service
          service: script.turn_on
          target:
            entity_id: script.luba_esci_dalla_base
        styles:
          card:
            - background: none
            - box-shadow: none
            - border: none
            - padding: 0
            - width: 200px
          grid:
            - grid-template-areas: "\"i\" \"n\""
            - place-items: center
            - row-gap: 4px
          icon:
            - width: 60px
            - height: 60px
            - color: "#22c55e"
          name:
            - color: white
            - font-weight: 800
            - font-size: 16px
            - text-shadow: 0 2px 6px rgba(0,0,0,0.9)
      - type: custom:button-card
        name: TORNA ALLA BASE
        icon: mdi:home-import-outline
        style:
          left: 80%
          top: 40%
          transform: translate(-50%, -50%)
        tap_action:
          action: call-service
          service: script.turn_on
          target:
            entity_id: script.luba_annulla_e_torna_alla_base
        styles:
          card:
            - background: none
            - box-shadow: none
            - border: none
            - padding: 0
            - width: 200px
          grid:
            - grid-template-areas: "\"i\" \"n\""
            - place-items: center
            - row-gap: 4px
          icon:
            - width: 60px
            - height: 60px
            - color: "#3b82f6"
          name:
            - color: white
            - font-weight: 800
            - font-size: 16px
            - text-shadow: 0 2px 6px rgba(0,0,0,0.9)
      - type: custom:button-card
        name: APRI PORTE
        icon: mdi:door-sliding-open
        style:
          left: 35%
          top: 90%
          transform: translate(-50%, -50%)
        tap_action:
          action: call-service
          service: script.turn_on
          target:
            entity_id: script.apri_porte_casetta
        styles:
          card:
            - background: none
            - box-shadow: none
            - border: none
            - padding: 0
            - width: 120px
          grid:
            - grid-template-areas: "\"i\" \"n\""
            - place-items: center
            - row-gap: 4px
          icon:
            - width: 40px
            - height: 40px
            - color: "#22c55e"
          name:
            - color: white
            - font-weight: 800
            - font-size: 13px
            - text-shadow: 0 2px 6px rgba(0,0,0,0.8)
      - type: custom:button-card
        name: CHIUDI PORTE
        icon: mdi:door-sliding
        style:
          left: 85%
          top: 90%
          transform: translate(-50%, -50%)
        tap_action:
          action: call-service
          service: script.turn_on
          target:
            entity_id: script.chiudi_porte_casetta
        styles:
          card:
            - background: none
            - box-shadow: none
            - border: none
            - padding: 0
            - width: 120px
          grid:
            - grid-template-areas: "\"i\" \"n\""
            - place-items: center
            - row-gap: 4px
          icon:
            - width: 40px
            - height: 40px
            - color: "#ef4444"
          name:
            - color: white
            - font-weight: 800
            - font-size: 13px
            - text-shadow: 0 2px 6px rgba(0,0,0,0.8)
      - type: custom:button-card
        name: STOP
        icon: mdi:pause-circle
        style:
          left: 60%
          top: 69%
          transform: translate(-50%, -50%)
        tap_action:
          action: call-service
          service: script.stop_porte_casetta
        styles:
          card:
            - background: none
            - box-shadow: none
            - border: none
            - padding: 0
            - width: 100px
          grid:
            - grid-template-areas: "\"i\" \"n\""
            - place-items: center
          icon:
            - width: 40px
            - height: 40px
            - color: "#f59e0b"
          name:
            - color: white
            - font-weight: 700
            - font-size: 10px
            - text-shadow: 0 2px 6px rgba(0,0,0,0.6)
  - type: conditional
    conditions:
      - entity: sensor.stato_porte_casetta_completo
        state: Chiusa
    elements:
      - type: image
        image: /local/casetta_chiusa.png
        style:
          top: 89%
          left: 60%
          transform: translate(-50%,-50%) scale(0.7,0.7)
  - type: conditional
    conditions:
      - entity: sensor.stato_porte_casetta_completo
        state: Aperta
    elements:
      - type: image
        image: /local/casetta_spalancata.png
        style:
          top: 89%
          left: 60%
          transform: translate(-50%,-50%) scale(0.7,0.7)
  - type: conditional
    conditions:
      - entity: sensor.stato_porte_casetta_completo
        state: In apertura
    elements:
      - type: image
        image: /local/casetta_apertura.gif
        style:
          top: 89%
          left: 60%
          transform: translate(-50%,-50%) scale(0.7,0.7)
  - type: conditional
    conditions:
      - entity: sensor.stato_porte_casetta_completo
        state: In chiusura
    elements:
      - type: image
        image: /local/casetta_chiusura.gif
        style:
          top: 89%
          left: 60%
          transform: translate(-50%,-50%) scale(0.7,0.7)

```
