### DISCUSSION TITLE
Automation to return the Mower back to docking station if the weather is not good.

### DISCUSSION THREAD

**Discussion by plamend** [mikey0000/Mammotion-HA#299] [Show and tell]
Hi, This is and example how I could contorl the execution of the tasks based on th weather conditions. 
This is more valuable when the task is built in the mobile app.
What is doing : 
The automation trigger is the device state,MODE_WORKING. If  one of the conditions is true the automation will execute. Condidions checks are for rainy, fog, lightning-rainy or the rain liba's sensor.
I have discovered that  during the fog condition Luba2 can not fix easy the position.
During the execution there is a delay of 9 sec just to give Luba some time to move away form the docking station. 
Than the task has been canceled by pushing the "Cancel current task" button.
The last action i  to send Luba back to the docking station.

I hope this will be valuable for others. 

```
alias: luba weather check
description: 
triggers:
  - trigger: state
    entity_id:
      - sensor.luba_dk_activity_mode
    from: null
    to: MODE_WORKING
conditions:
  - condition: or
    conditions:
      - condition: state
        entity_id: weather.openweathermap
        state: rainy
      - condition: state
        entity_id: weather.openweathermap
        state: fog
      - condition: state
        entity_id: weather.openweathermap
        state: lightning-rainy
      - condition: state
        entity_id: weather.openweathermap
        state: hail
      - condition: state
        entity_id: switch.luba_dk_rain_detection_on_off
        state: "on"
    enabled: true
actions:
  - delay:
      hours: 0
      minutes: 0
      seconds: 9
      milliseconds: 0
  - device_id: ef484ea150b571b8b69a36d1d2a5cf05
    domain: button
    entity_id: 7803b981732b0d45903edd9a95fcab26
    type: press
  - action: lawn_mower.dock
    metadata: {}
    data: {}
    target:
      device_id: ef484ea150b571b8b69a36d1d2a5cf05
mode: single
```
