### DISCUSSION TITLE
Options for Mowing tasks using the integration

### DISCUSSION THREAD

**Discussion by roninf** [mikey0000/Mammotion-HA#321] [Q&A]
Can someone tell what the different options for mowings tasks (automations) exactly mean? (yaml mode)

      border_mode: 0
      speed: 0.3
      channel_mode: 3
      channel_width: 22
      rain_tactics: 1
      toward_mode: 0
      mowing_laps: 1
      obstacle_laps: 2

Are there even more ?

I am asking because i have set up a task with checkerboard mowing path (in the gui) but the robot did the the same route twice.

BR and thanks!

**Comment by roninf** [comment]
Would the following be correct for Checkerboard ?

  - data:
      is_mow: true
      is_dump: false
      is_edge: true
      border_mode: 0
      speed: 0.3
      channel_mode: 1
      channel_width: 22
      rain_tactics: 1
      toward_mode: 0
      mowing_laps: 2
      obstacle_laps: 2

**Reply by mikey0000** [reply]
What mower do you have?

**Reply by mikey0000** [reply]
Also yes 1 for channel mode is chessboard

```
action: mammotion.start_mow
target:
  device_id:
    - 504079cf9df5509d87e04481a28c74f5
data:
  is_mow: false
  is_dump: false
  border_mode: 0
  speed: 0.2
  ultra_wave: 10
  channel_mode: 1
  channel_width: 20
  toward_mode: 0
  mowing_laps: 1
  obstacle_laps: 2
  start_progress: 0
  areas:
    - switch.thou_doth_moweth_area_back_backyard
  blade_height: 70
  toward: 0
  toward_included_angle: 45
```
