### DISCUSSION TITLE
Reliability of  battery status information

### DISCUSSION THREAD

**Discussion by labupps** [mikey0000/Mammotion-HA#338] [General]
Hi,

I have an issue with my Luba2 which is facing battery charging issues, it stops charging at approx 59%.

Strange enough, there is an update of the android app today and since then it says 100% battery whereas it shows still 59% on HA.

Who is telling the truth? Is it a nice trick from the app to simulate a problem solved (I am not the only one with it).

![image](https://github.com/user-attachments/assets/9a756982-c14d-457c-b07e-48bb85f0b3f3)

I have to say this makes me sceptical.

By the way, nice job with this app.

**Comment by mikey0000** [comment]
Thanks, not sure who's telling the truth, depends when the last bit of info was received from the mower. HA just displays what comes back from the mower so either it failed to get data or it's telling the truth.

**Reply by labupps** [reply]
I do suspect an issue with the refresh as no values are changing. I hope this is the case and not a fool on the app.

**Reply by labupps** [reply]
Solved as due to a factory reset of the robot the robot was no more visible on the HA account. Strange enough it kept some old values on the account. Got to rebind on the app under the HA account.

**Comment by holger1414** [comment]
Completely off-topic, but what is the card with the satellite photo?
:)

**Reply by labupps** [reply]
![image](https://github.com/user-attachments/assets/017db701-e318-4360-b135-fb0465918ef9)

Here is the code for mine

```
type: custom:map-card
focus_entity: device_tracker.luba_loetlo_luba_............
zoom: 18
entities:
  - entity: device_tracker.luba_loetlo_luba_.................
    size: 20
    display: marker
    history_start: 24 hours ago
    history_line_color: blue
    history_show_dots: false
card_size: 9
tile_layers:
  - url: >-
      https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}
default_zoom: 18
tile_layer_options:
  maxZoom: 20
theme_mode: light
```
