### ISSUE TITLE
mammotion.start_mow can't handle data_template any longer

### ISSUE THREAD

**Issue by anders-vestergaard** [mikey0000/Mammotion-HA#185]
### The problem

I'm triggering my mow with a data_template. It was possible when I used 0.1.70 but it gives me this error now:
"This action requires field areas, which must be provided under 'data:'"

I've tested using Developer Tools and automation. When I hardcode the values it passes, but when I template it fails.

### What Mammotion mower are you using?

Luba 2

### What version of the Mammotion intergration are you using?

0.1.72

### What version of Home Assistant Core are you running?

core-2024.10.3

**Comment by mikey0000** [comment]
Can you give an example of this template please.

**Comment by anders-vestergaard** [comment]
This template in data_template worked previously:

```
  service: mammotion.start_mow
  data_template:
    job_mode: 1
    speed: 0.5
    ultra_wave: 2
    channel_mode: 0
    channel_width: 30
    rain_tactics: 1
    blade_height: "{{ states('input_number.system_lawn_mower_cutting_height') | int }}"
    toward: "{{ states('input_number.system_lawn_mower_current_path') | int }}"
    toward_mode: 1
    start_progress: >
      {% if states('input_number.system_lawn_mower_progress') | int != 0 %}
        {{ (states('input_number.system_lawn_mower_progress') | int) - 1 }}
      {% else %}
        0
      {% endif %}
    areas:
      - switch.garden_mower_1_have
  target:
    entity_id: lawn_mower.garden_mower_1_mower
```

It's the start_progress part that is no longer working. The other state insertions (for blade_height and toward) work as expected.

I’ve created a workaround by moving the if-else logic to a separate action before the mammotion.start_mow action. I store the result in an input_boolean or input_number, and then I use that state directly in the mammotion.start_mow call. This allows me to bypass the issue and still use the value in the mowing action.
