### ISSUE TITLE
BLE setup correct

### ISSUE THREAD

**Issue by guensen0** [mikey0000/Mammotion-HA#224]
### The problem

Hi,

nice integration. Based on you documentation, I try to run it with BLE proxy. Is this still needed or outdated already?
I setup a ESP32 with following settings:
```
binary_sensor:
  - platform: ble_presence
    mac_address: XX:XX:XX:XX:XX:)B
    name: "ESP32 BLE Presence Yuka Mini"
  - platform: ble_presence
    mac_address: XX:XX:XX:XX:XX:16
    name: "ESP32 BLE Presence RTK"

ble_client:
  - mac_address: XX:XX:XX:XX:XX:9B
    id: yuka_ble_client
    auto_connect: true
    on_connect:
      then:
        - logger.log: "Connected to Mammotion Lawn Mower"
    on_disconnect:
      then:
        - logger.log: "Disconnected from Mammotion Lawn Mower"
  - mac_address: XX:XX:XX:XX:XX:16
    id: RTK
    auto_connect: true
    on_connect:
      then:
        - logger.log: "Connected to Mammotion RTK"
    on_disconnect:
      then:
        - logger.log: "Disconnected from Mammotion RTK"
```

in contrast to your example in the WIKI i had to adjust the code a bit. The Esp is running ans also the log shows a successful connection:

```
[15:22:55][C][bluetooth_proxy.connection:017]: BLE Connection:
[15:22:55][C][esp32_ble_client:048]:   Address: 
[15:22:55][C][esp32_ble_client:049]:   Auto-Connect: FALSE
[15:22:55][C][esp32_ble_client:083]:   State: IDLE
[15:22:55][C][ble_client:027]: BLE Client:
[15:22:55][C][esp32_ble_client:048]:   Address: XX:XX:XX:XX:XX:9B
[15:22:55][C][esp32_ble_client:049]:   Auto-Connect: TRUE
[15:22:55][C][esp32_ble_client:048]:   Address: XX:XX:XX:XX:XX:16
[15:22:55][C][esp32_ble_client:083]:   State: ESTABLISHED
```
i also generated a binary sensor to track which BT device is connected and also that works, but when I check the history I see that its always connect / disconnect every 5 mins... is that common?

<img width="586" alt="Image" src="https://github.com/user-attachments/assets/e8e7581e-5ada-4ad1-9d5e-f43fe3263006" />

is something wrong in my configuration?
I already had my Yuka mini connected to HA without the BLE proxy. Are additional steps needed? e.g remove the device from mammotion and configure again?

Sorry for all my questions and thank you for your work.
Stefan

### What Mammotion mower are you using?

Yuka

### What version of the Mammotion intergration are you using?

v0.1.110

### What version of Home Assistant Core are you running?

core-2025.2.5
