### ISSUE TITLE
Difficulty with bluetooth proxy

### ISSUE THREAD

**Issue by mpurv** [mikey0000/Mammotion-HA#276]
### The problem

Hi everyone, 

I am completely new to HA and have zero experience with microcontrollers and programming, so apologies if the fix to this is obvious or I’ve posted this in the wrong place.

Thanks for the awesome work with the mammotion integration! I have problems with luba dropping off the wifi network, which stops me using it when I am away. I set up HA with the primary purpose of having the option to remotely control my luba 1 via a Bluetooth proxy.

I have followed the setup instructions in the repository for both the integration and the proxy. I’ve flashed the ESP32 with the suggested YAML (though with some minor alterations based on my reading of the ESPHome component syntax, as the exact copy couldn’t be validated). 

The mammotion integration can get data from luba, but only via wifi, and only at the time that HA is restarted (i.e. it doesn’t refresh). I cannot control luba with the integration. The BLE RSSI shows no signal when my phone has Bluetooth switched off. So, I think this is a problem with the bluetooth proxy rather than the integration per se.

The proxy’s log shows it is recurrently scanning, but not making any connections. Looking at the ESP32 device diagnostics, it looks like Luba is advertising. Unfortunately, this is the limit of my interpretation. Any help would be much appreciated, as I don’t know what else to do.

This is the [config YAML](https://drive.google.com/file/d/19FA_fPqp3h8dBii1QlYQzxl5MoDoZJC4/view?usp=sharing)
This is one of the earlier [config flashing](https://drive.google.com/file/d/1VBUkzI6ePnFCxtELXosqSRb6oVJcX7a-/view?usp=sharing) logs (seems to work, starts scanning indefinitely)
This is another [config update log](https://drive.google.com/file/d/1CV9ukWuAMxO6fWPQRbRiP3JpWY5jIW5x/view?usp=sharing) for the ESP32 (again seems to work, but indefinitely starts scanning at the end)
This is the [web interface log](https://drive.google.com/file/d/1AJc7bghfv5-VezFhWrHhqvYBNTON3j47/view?usp=sharing,) for the proxy (indefinite scanning)

Here are the diagnostics logs I have so far 
-	the integration’s [debugger log](https://drive.google.com/file/d/1oHcFrpDes0lTfioaq_ENQ-YYRim_uUv-/view?usp=drive_link)
-	the ESP32 [device diagnostics](https://drive.google.com/file/d/1Vuhlsco9nG8KubI3U5Dn8KfopWYbEWyH/view?usp=drive_link)

Let me know if more information is needed. Thanks in advance!

### What Mammotion mower are you using?

Luba 1

### What version of the Mammotion intergration are you using?

0.2.18

### What version of Home Assistant Core are you running?

2025.4.1

**Comment by mikey0000** [comment]
you don't need
```
# enable the ESP32 to act as a proxy only for your lawn mower
ble_client:
  - mac_address: E0:5A:1B:5A:EE:2C  # Replace with your lawn mower's MAC address
    id: mower_ble_client

    on_connect:
      then:
        - logger.log: "Connected to Mammotion Lawn Mower"

    on_disconnect:
      then:
        - logger.log: "Disconnected from Mammotion Lawn Mower"

esp32_ble_server:
  services:
    - uuid: '0000ffff-0000-1000-8000-00805f9b34fb'
```
its optional
try removing that and see if that solves your issues.
