### ISSUE TITLE
problem with esp32 config

### ISSUE THREAD

**Issue by serpentes80** [mikey0000/Mammotion-HA#385]
### The problem

i get 

 [services] is an invalid option for [ble_client]. Please check the indentation.

and if i leave the 2nd part of the config out, it doesn't seem to connect

### What Mammotion mower are you using?

Yuka mini

### What version of the Mammotion intergration are you using?

0.2.55

### What version of Home Assistant Core are you running?

2025.6

**Comment by chrbratt** [comment]
A bit late reply but encountered the same problem and solved it with this code. It seems that the documentation is quite outdated and not really up-to-date

```
substitutions:
  name: esp32-ble-proxy
  friendly_name: Lawnmover Proxy

packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
  
  ap:
    ssid: "Esp32-ble-proxy"
    password: "12345678"

api:
  encryption:
    key: !secret api_encryption_key

logger:
  level: WARN

ota:
  - platform: esphome

improv_serial:

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          ESP_LOGI("ble_scan", "BLE device: %s (%s) RSSI: %d dBm", 
                   x.address_str().c_str(), x.get_name().c_str(), x.get_rssi());
          
          if (x.address_str() == "xx:xx:xx:xx:xx:xx") {
            ESP_LOGW("mammotion", "🌟 Mammotion found! RSSI: %d dBm", x.get_rssi());
          }

ble_client:
  - mac_address: "xx:xx:xx:xx:xx:xx"
    id: mower_ble_client
    on_connect:
      then:
        - logger.log: 
            format: "🔗 Connected to Mammotion Lawn Mower!"
            level: WARN
    on_disconnect:
      then:
        - logger.log: 
            format: "❌ Disconnected from Mammotion Lawn Mower"
            level: WARN

bluetooth_proxy:
  active: true

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

button:
  - platform: restart
    name: "Reboot Mammotion Proxy"
```
